[package]
name = "cscsca"
authors = ["Charles Feyen"]
version = "0.14.4"
edition = "2024"
readme = "README.md"
keywords = ["linguistics", "conlang"]
categories = ["command-line-utilities"]
description = "Charles' Super Cool Sound Change Applier - A tool for simulating phonetic evolution"

[features]
docs = []
ansi = []
gen_vscode_grammar = []

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
panic = "abort"

[dependencies]