[package]
name = "cscsca"
version = "0.6.3"
edition = "2024"
description = "Charles' Super Cool Sound Change Applier - A tool for simulating phonemic evolution"
readme = "README.md"
authors = ["Charles Feyen"]

[features]
no_ansi = []

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
panic = "abort"

[dependencies]